spring:
  kafka:
    consumer:
      bootstrap-servers:
        - 3.38.212.52:9092
        - 3.38.212.52:9093
        - 3.38.212.52:9094
      group-id: springboot
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers:
        - 3.38.212.52:9092
        - 3.38.212.52:9093
        - 3.38.212.52:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer